---
# Everything else is installed via brew bundle.

packages_apt_bootstrap_packages:
  - build-essential
  - curl
  - git
  - procps
  - file

packages_pacman_bootstrap_packages:
  - base-devel
  - curl
  - git

packages_dnf_bootstrap_packages:
  - gcc
  - gcc-c++
  - make
  - curl
  - git
