---
- name: Clone external git repos
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    update: "{{ external_repos_update | default(false) }}"
    version: "{{ item.version | default('HEAD') }}"
  loop: "{{ external_repos }}"

- name: Check if glow already installed
  ansible.builtin.stat:
    path: "{{ local_bin }}/glow"
  register: external_glow_bin

- name: Download glow binary (Linux x86_64)
  ansible.builtin.get_url:
    url: "https://github.com/charmbracelet/glow/releases/download/v2.1.2/glow_2.1.2_Linux_x86_64.tar.gz"
    dest: /tmp/glow.tar.gz
    checksum: sha256:6063d4f2af8a82a5f4bba0831e165de9381660aa8b41df4816d0106a265b07d5
    mode: "0644"
  when:
    - ansible_facts["os_family"] != "Darwin"
    - ansible_facts["architecture"] == "x86_64"
    - not external_glow_bin.stat.exists

- name: Extract glow binary (Linux)
  ansible.builtin.unarchive:
    src: /tmp/glow.tar.gz
    dest: "{{ local_bin }}"
    include: glow
    remote_src: true
  when:
    - ansible_facts["os_family"] != "Darwin"
    - ansible_facts["architecture"] == "x86_64"
    - not external_glow_bin.stat.exists

- name: Check if Monaspace fonts installed
  ansible.builtin.stat:
    path: "{{ xdg_data_home }}/fonts/Monaspace"
  register: external_monaspace_dir

- name: Download Monaspace fonts (Linux)
  ansible.builtin.get_url:
    url: "https://github.com/githubnext/monaspace/releases/download/v1.400/monaspace-v1.400.zip"
    dest: /tmp/monaspace.zip
    mode: "0644"
  when:
    - ansible_facts["os_family"] != "Darwin"
    - not external_monaspace_dir.stat.exists

- name: Create fonts dir
  ansible.builtin.file:
    path: "{{ xdg_data_home }}/fonts/Monaspace"
    state: directory
    mode: "0755"
  when:
    - ansible_facts["os_family"] != "Darwin"
    - not external_monaspace_dir.stat.exists

- name: Extract Monaspace fonts (Linux)
  ansible.builtin.unarchive:
    src: /tmp/monaspace.zip
    dest: "{{ xdg_data_home }}/fonts/Monaspace"
    remote_src: true
    extra_opts: ["--strip-components=1"]
  notify: Refresh font cache
  when:
    - ansible_facts["os_family"] != "Darwin"
    - not external_monaspace_dir.stat.exists
